backend_options:
  mpi:
    mpiflags: ''  # Optional: things like -H or --hostfile
  ssh:
    hosts: ''     # One or more hosts to log in to (defaults to localhost)
sys_spec_commands:   # Shell commands to generate SUT description for MD file
  Host: 'hostname'
  OS: 'uname -posr'
  CPU: 'lscpu'
  RAM: 'free -g'
  GPU: 'nvidia-smi'
